export default iconNames = ['anchor', 
                            'arrowUp',
                            'arrowDown',
                            'at-sign',
                            'award' ,
                            'book' ,
                            'battery',
                            'briefcase',
                            'camera',
                            'clipBoard',
                            'coffee',
                            'dollar',
                            'edit',
                            'fileText',
                            'github',
                            'gift',
                            'instagram',
                            'mail',
                            'music',
                            'user',
                            'droplet',
                            'codePen',
                            'smile',
                            'edit',
                            'video',
                            'search',
                            'editar2']
